apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    job: results
    app: results
spec:
  selector:
    app: results
  ports:
    - name: web
      port: 8085
      protocol: TCP
      targetPort: 8085
      nodePort: 30005
  type: NodePort

# ---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: results-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: web
      path: /metrics
  selector:
    matchLabels: 
      app: results