apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:  
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: voting
        image: {{ .Values.image.repository }} : {{ .Values.image.tag }}
        ports:
        - containerPort: 8083
        env:
        - name: RESULTS_SERVICE_URL
          value: "http://voting-service:30005/results"
        - name: REDIS_ADDR
          value: "redis:6379"