apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    job: redis
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP

# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: redis-service-monitor
#   labels:
#     release: prometheus
#     app: prometheus
# spec:
#   jobLabel: job
#   endpoints:
#     - interval: 30s
#       port: web
#       path: /metrics
#   selector:
#     matchLabels: 
#       app: redis