apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    job: postgres
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: web
      port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP

# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: postgres-service-monitor
#   labels:
#     release: prometheus
#     app: prometheus
# spec:
#   jobLabel: job
#   endpoints:
#     - interval: 30s
#       port: web
#       path: /metrics
#   selector:
#     matchLabels: 
#       app: postgres