apiVersion: v1
kind: Service
metadata:
  # name: {{ .Release.Name }}-service
  name: voting-service
  labels:
    job: voting
    app: voting
spec:
  type: NodePort
  selector:
    app: voting
  ports:
    - port: 8083  
      targetPort: 8083
      nodePort: 30004
      protocol: TCP
  

# ---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: voting-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: web
      path: /metrics
  selector:
    matchLabels: 
      app: voting